### ISSUE TITLE
Rug-polynomial not calling fmpz_mod_ctx_clear

### ISSUE THREAD

**Issue by ajirving** [alex-ozdemir/flint-rs#20]
The Drop trait for ModPoly doesn't clear the ctx which causes a memory leak.  You can see this with Valgrind if you use a modulus with more than 1 limb.

**Comment by wjyoumans** [comment]
I made a quick fix but its up to @alex-ozdemir to publish the new crate (I bumped the version already).

Check out https://github.com/wjyoumans/inertia-core if you're interested in a general high-level Rust wrapper for Flint.
