### ISSUE TITLE
Error while running `cargo test --lib --release`

### ISSUE THREAD

**Issue by tbrezot** [alex-ozdemir/flint-rs#9]
Hello,

On the `master` branch, `cargo test --lib` runs successfully, but not `cargo test --lib --release` which throws the following error:

```
$ cargo test --lib --release
    Finished release [optimized] target(s) in 0.01s
     Running unittests (/home/brezot/Documents/code/flint-rs/target/release/deps/flint_sys-05ec743af968ead8)

running 3 tests
test tests::it_works ... ok
test tests::try_it ... ok
free(): double free detected in tcache 2
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/home/brezot/Documents/code/flint-rs/target/release/deps/flint_sys-05ec743af968ead8` (signal: 6, SIGABRT: process abort signal)
```

I ran the test on an `Ubuntu 20.04.3 LTS` platform.

Any idea what could cause this ?

**Comment by wjyoumans** [comment]
See the linked PR. `cargo test --lib --release` should work fine now, the faulty test was removed (it's an issue with flint/GMP conversions so not too important for now).
